#spring.application.name=SpringRedisCache
## Create a table and drop when the application closes.
#spring.jpa.hibernate.ddl-auto=create-drop
## The location where database is running
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/cars
#spring.datasource.username=root
#spring.datasource.password=sumit
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.show-sql: true
#
#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
